(if (eq t (and))
  (if (eq t (and t))
    (if (eq t (and t t))
      (if (eq t (and t t t))
	(if (eq () (and ()))
	  (if (eq () (and () ()))
	    (if (eq () (and () () ()))
	      (if (eq () (and () t t))
		(if (eq () (and t () t))
		  (if (eq () (and t t ()))
		      t
		    (error "(and t t ()) must return ()"))
		  (error "(and t () t()) must return ()"))
		(error "(and () t t) must return ()"))
	      (error "(and () () ()) must return ()"))
	    (error "(and () ()) must return ()"))
	  (error "(and ()) must return ()"))
	(error "(and t t t) must return t"))
      (error "(and t t) must return t"))
    (error "(and t) must return t"))
  (error "(and) must return t"))
