(if (eq () (and))
    (error "(and) must return t")
  (if (eq () (and t))
      (error "(and t) must return t")
    (if (eq () (and t t))
	(error "(and t t) must return t")
      (if (eq () (and t t t))
	  (error "(and t t t) must return t")
	(if (eq t (and ()))
	    (error "(and ()) must return ()")
	  t)))))
